"""create rental system tables

Revision ID: a9cb5f1c077d
Revises: 
Create Date: 2026-06-21 15:02:44.181553

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a9cb5f1c077d'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('area',
    sa.Column('code', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('uuid', sa.String(length=36), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('details', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('uuid')
    )
    op.create_index(op.f('ix_area_code'), 'area', ['code'], unique=False)
    op.create_table('document',
    sa.Column('ref_table', sa.String(), nullable=False),
    sa.Column('ref_uuid', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('path', sa.String(), nullable=False),
    sa.Column('uuid', sa.String(length=36), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('details', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('uuid')
    )
    op.create_index(op.f('ix_document_ref_table'), 'document', ['ref_table'], unique=False)
    op.create_index(op.f('ix_document_ref_uuid'), 'document', ['ref_uuid'], unique=False)
    op.create_table('renter',
    sa.Column('code', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('tel', sa.String(), nullable=True),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('uuid', sa.String(length=36), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('details', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('uuid')
    )
    op.create_index(op.f('ix_renter_code'), 'renter', ['code'], unique=False)
    op.create_table('user',
    sa.Column('code', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('password', sa.String(), nullable=False),
    sa.Column('last_login', sa.DateTime(timezone=True), nullable=True),
    sa.Column('uuid', sa.String(length=36), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('details', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('uuid')
    )
    op.create_index(op.f('ix_user_code'), 'user', ['code'], unique=False)
    op.create_table('contract',
    sa.Column('area', sa.String(length=36), nullable=False),
    sa.Column('renter', sa.String(length=36), nullable=False),
    sa.Column('ref_contract', sa.String(length=36), nullable=True),
    sa.Column('start', sa.Date(), nullable=True),
    sa.Column('end', sa.Date(), nullable=True),
    sa.Column('payment_date', sa.Date(), nullable=True),
    sa.Column('uuid', sa.String(length=36), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('details', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['area'], ['area.uuid'], ),
    sa.ForeignKeyConstraint(['ref_contract'], ['contract.uuid'], ),
    sa.ForeignKeyConstraint(['renter'], ['renter.uuid'], ),
    sa.PrimaryKeyConstraint('uuid')
    )
    op.create_index(op.f('ix_contract_area'), 'contract', ['area'], unique=False)
    op.create_index(op.f('ix_contract_ref_contract'), 'contract', ['ref_contract'], unique=False)
    op.create_index(op.f('ix_contract_renter'), 'contract', ['renter'], unique=False)
    op.create_table('meter',
    sa.Column('type', sa.String(), nullable=True),
    sa.Column('value', sa.Numeric(precision=14, scale=4), nullable=True),
    sa.Column('area', sa.String(length=36), nullable=False),
    sa.Column('net_value', sa.Numeric(precision=14, scale=4), nullable=True),
    sa.Column('uuid', sa.String(length=36), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('details', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['area'], ['area.uuid'], ),
    sa.PrimaryKeyConstraint('uuid')
    )
    op.create_index(op.f('ix_meter_area'), 'meter', ['area'], unique=False)
    op.create_table('invoice',
    sa.Column('contract', sa.String(length=36), nullable=False),
    sa.Column('invoice_date', sa.Date(), nullable=True),
    sa.Column('payment_date', sa.Date(), nullable=True),
    sa.Column('uuid', sa.String(length=36), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('details', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['contract'], ['contract.uuid'], ),
    sa.PrimaryKeyConstraint('uuid')
    )
    op.create_index(op.f('ix_invoice_contract'), 'invoice', ['contract'], unique=False)
    op.create_table('payment',
    sa.Column('invoice', sa.String(length=36), nullable=False),
    sa.Column('amount', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('payment_date', sa.Date(), nullable=True),
    sa.Column('type', sa.String(), nullable=True),
    sa.Column('overdue_amount', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('ref_payment', sa.String(length=36), nullable=True),
    sa.Column('meter', sa.String(length=36), nullable=True),
    sa.Column('uuid', sa.String(length=36), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('details', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['invoice'], ['invoice.uuid'], ),
    sa.ForeignKeyConstraint(['meter'], ['meter.uuid'], ),
    sa.ForeignKeyConstraint(['ref_payment'], ['payment.uuid'], ),
    sa.PrimaryKeyConstraint('uuid')
    )
    op.create_index(op.f('ix_payment_invoice'), 'payment', ['invoice'], unique=False)
    op.create_index(op.f('ix_payment_meter'), 'payment', ['meter'], unique=False)
    op.create_index(op.f('ix_payment_ref_payment'), 'payment', ['ref_payment'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_payment_ref_payment'), table_name='payment')
    op.drop_index(op.f('ix_payment_meter'), table_name='payment')
    op.drop_index(op.f('ix_payment_invoice'), table_name='payment')
    op.drop_table('payment')
    op.drop_index(op.f('ix_invoice_contract'), table_name='invoice')
    op.drop_table('invoice')
    op.drop_index(op.f('ix_meter_area'), table_name='meter')
    op.drop_table('meter')
    op.drop_index(op.f('ix_contract_renter'), table_name='contract')
    op.drop_index(op.f('ix_contract_ref_contract'), table_name='contract')
    op.drop_index(op.f('ix_contract_area'), table_name='contract')
    op.drop_table('contract')
    op.drop_index(op.f('ix_user_code'), table_name='user')
    op.drop_table('user')
    op.drop_index(op.f('ix_renter_code'), table_name='renter')
    op.drop_table('renter')
    op.drop_index(op.f('ix_document_ref_uuid'), table_name='document')
    op.drop_index(op.f('ix_document_ref_table'), table_name='document')
    op.drop_table('document')
    op.drop_index(op.f('ix_area_code'), table_name='area')
    op.drop_table('area')
    # ### end Alembic commands ###
